export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const FETCH_MORE_ARTICLES = 'FETCH_MORE_ARTICLES';
export const FETCH_AUTHORS_PARTIAL = 'FETCH_AUTHOR_PARTIAL';
export const FETCH_AUTHORS_FULL = 'FETCH_AUTHOR_FULL';
export const RESET_DATA = 'RESET_DATA'
